(()=>{
  "use strict";
  const $=id=>document.getElementById(id);
  let section="overview";
  let state=null;
  const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const num=(value,digits=1)=>Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{maximumFractionDigits:digits}):"—";
  const pill=value=>`<span class="pill ${esc(String(value||"UNKNOWN").toUpperCase())}">${esc(value||"UNKNOWN")}</span>`;
  const json=value=>esc(JSON.stringify(value??{},null,2));
  async function api(url,options={}){const response=await fetch(url,options);let payload={};try{payload=await response.json()}catch{}if(!response.ok||payload.success===false)throw new Error(payload.message||payload.error||`HTTP ${response.status}`);return payload}
  function cards(entries){return `<div class="grid">${entries.map(([label,value,klass=""])=>`<article class="card"><span>${esc(label)}</span><strong class="${klass}">${esc(value)}</strong></article>`).join("")}</div>`}
  function table(headers,rows){if(!rows.length)return '<div class="empty">No records available for this surface.</div>';return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.join("")}</tbody></table></div>`}
  function overview(){const c=state.completion||{},w=state.workspaces||{},q=state.mission_queue||{},code=state.code_intelligence||{},memory=state.memory?.data||{},events=state.market_events||{};const pct=Number(c.repository_completion_percent||0);return cards([["REPOSITORY COMPLETION",`${num(pct)}%`,pct>=95?"ok":pct>=80?"warn":"bad"],["WORKSPACES",`${w.workspace_count||0}`],["PENDING APPROVALS",`${state.approvals?.pending?.length||0}`,state.approvals?.pending?.length?"warn":"ok"],["MISSION QUEUE",`${q.counts?.QUEUED||0} queued`],["PYTHON INDEX",`${code.files||0} files`],["MEMORY",`${memory.records||0} records`],["MARKET EVENTS",`${events.published||0} published`],["LIVE EXECUTION","LOCKED","bad"]])+`<section class="section"><div class="section-head"><h2>Repository completion</h2><small>${c.repository_complete?"Repository-controlled scope complete":"Remaining repository work is visible below"}</small></div><div class="progress"><i style="width:${Math.max(0,Math.min(100,pct))}%"></i></div></section>`+`<section class="section"><div class="section-head"><h2>Remaining repository items</h2></div>${matrixRows(c.remaining_repository_items||[])}</section>`+`<section class="section"><div class="section-head"><h2>External blockers — not falsely counted as code defects</h2></div>${matrixRows(c.external_blockers||[])}</section>`}
  function matrixRows(rows){return table(["CAPABILITY","DOMAIN","STATUS","DETAIL","NEXT"],rows.map(row=>`<tr><td><b>${esc(row.title||row.key)}</b><br><small>${esc(row.key||"")}</small></td><td>${esc(row.domain||"")}</td><td>${pill(row.status)}</td><td>${esc(row.detail||"")}</td><td>${esc(row.next_action||"")}</td></tr>`))}
  function matrix(){return matrixRows(state.completion?.items||[])}
  function runtime(){const rows=state.workspaces?.rows||[];return cards([["HEALTH SOURCE",state.workspaces?.health_source||"—"],["OVERALL",state.workspaces?.health_contract?.overall||"—",state.workspaces?.health_contract?.overall==="READY"?"ok":"warn"],["PROTECTED CORE",state.workspaces?.safety?.protected_core||"REQUIRED"],["BROKER ORDERS",state.workspaces?.safety?.automatic_broker_order?"ENABLED":"LOCKED","bad"]])+`<section class="section">${table(["WORKSPACE","GROUP","STATUS","SAFETY","ACTIVITY"],rows.map(row=>`<tr><td><b>${esc(row.title)}</b></td><td>${esc(row.group)}</td><td>${pill(row.status)}</td><td>${esc(row.safety)}</td><td>${esc(row.activity||"")}</td></tr>`))}</section>`}
  function approvals(){const rows=state.approvals?.pending||[];return table(["APPROVAL","ACTION","EXPIRES","STATUS","OPERATOR ACTION"],rows.map(row=>`<tr><td>${esc(row.id)}</td><td><b>${esc(row.action)}</b><br><small>${esc(row.reason||"")}</small></td><td>${esc(row.expires_at||"")}</td><td>${pill(row.status)}</td><td><div class="approval-actions"><button data-approve="${esc(row.id)}">APPROVE</button><button class="reject" data-reject="${esc(row.id)}">REJECT</button></div></td></tr>`))}
  function missions(){const latest=state.missions||{},queue=state.mission_queue||{};return cards([["MISSION COUNT",`${latest.mission_count||0}`],["LATEST",latest.latest_status||"READY"],["QUEUED",`${queue.counts?.QUEUED||0}`],["LEASED",`${queue.counts?.LEASED||0}`]])+`<section class="section"><div class="section-head"><h2>Resumable local queue</h2><small>Queue state only; external actions remain approval-gated.</small></div>${table(["ID","TITLE / OBJECTIVE","PRIORITY","STATUS","ATTEMPTS"],(queue.items||[]).map(row=>`<tr><td>${esc(row.queue_id)}</td><td><b>${esc(row.title||"Mission")}</b><br><small>${esc(row.objective)}</small></td><td>${esc(row.priority)}</td><td>${pill(row.status)}</td><td>${esc(row.attempts)}</td></tr>`))}</section>`}
  function engineering(){const code=state.code_intelligence||{};return cards([["FILES",`${code.files||0}`],["LINES",`${code.lines||0}`],["FUNCTIONS",`${code.functions||0}`],["CLASSES",`${code.classes||0}`],["PARSE ERRORS",`${code.parse_errors||0}`,code.parse_errors?"bad":"ok"],["AUTO EDITING",code.automatic_editing?"ON":"OFF","ok"]])+`<section class="section"><div class="search"><input id="codeQuery" placeholder="Search symbols/imports, e.g. paper portfolio risk"><button id="codeSearch">SEARCH AST INDEX</button></div><div id="codeResults" class="empty">Enter a repository symbol or concept. Search is read-only and AST based.</div></section>`}
  function memory(){const m=state.memory?.data||state.memory||{};return cards([["DATABASE",m.exists?"PRESENT":"NOT CREATED",m.exists?"ok":"warn"],["RECORDS",`${m.records||0}`],["SIZE",`${num((m.bytes||0)/1024,1)} KB`],["MUTATION","NONE FROM THIS VIEW","ok"]])+`<section class="section"><div class="panel"><div class="section-head"><h2>Memory kinds</h2></div><pre>${json(m.kinds||{})}</pre></div></section>`}
  function models(){const m=state.model_router||{};return cards([["TELEMETRY EVENTS",`${m.event_count||0}`],["PROFILES OBSERVED",`${m.profiles?.length||0}`],["PRIVACY CHANGED",m.privacy_policy_changed?"YES":"NO","ok"],["CLOUD AUTO-ENABLED",m.cloud_enabled_by_telemetry?"YES":"NO","ok"]])+`<section class="section">${table(["PROFILE","EVENTS","SUCCESS RATE","AVG LATENCY","AVG QUALITY"],(m.profiles||[]).map(row=>`<tr><td>${esc(row.profile_id)}</td><td>${esc(row.events)}</td><td>${row.success_rate==null?"—":num(row.success_rate*100)+"%"}</td><td>${row.average_latency_ms==null?"—":num(row.average_latency_ms)+" ms"}</td><td>${row.average_quality_score==null?"—":num(row.average_quality_score,3)}</td></tr>`))}</section>`}
  function markets(){const m=state.market_events||{};return cards([["PUBLISHED",`${m.published||0}`],["RETAINED",`${m.retained||0}`],["SUBSCRIBER ERRORS",`${m.subscriber_errors||0}`,m.subscriber_errors?"warn":"ok"],["LIVE EXECUTION","FALSE","ok"]])+`<section class="section">${table(["TYPE","PROVIDER","SYMBOL","TIMEFRAME","VERIFIED","STALE"],(m.events||[]).slice().reverse().map(row=>{const d=row.datum||{};return `<tr><td>${esc(row.event_type||d.event_type)}</td><td>${esc(d.provider)}</td><td>${esc(d.provider_symbol)}</td><td>${esc(d.timeframe)}</td><td>${esc(d.verified)}</td><td>${esc(d.stale)}</td></tr>`}))}</section>`}
  function strategies(){const s=state.strategy_governance||{};return cards([["RESEARCH RECORDS",`${s.records?.length||0}`],["PAPER CHAMPIONS",`${Object.keys(s.paper_champions||{}).length}`],["PRODUCTION PROMOTION",s.governance?.automatic_production_promotion?"AUTO":"DISABLED","ok"],["LIVE PROMOTION",s.governance?.automatic_live_promotion?"AUTO":"DISABLED","ok"]])+`<section class="section">${table(["SYMBOL","TF","REGIME","STRATEGY","STATUS","CREATED"],(s.records||[]).slice().reverse().map(row=>`<tr><td>${esc(row.symbol)}</td><td>${esc(row.timeframe)}</td><td>${esc(row.regime)}</td><td>${esc(row.candidate?.name||"")}</td><td>${pill(row.status)}</td><td>${esc(row.created_at||"")}</td></tr>`))}</section>`}
  const renderers={overview,matrix,runtime,approvals,missions,engineering,memory,models,markets,strategies};
  function bind(){document.querySelectorAll("[data-approve]").forEach(button=>button.addEventListener("click",()=>approval(button.dataset.approve,true)));document.querySelectorAll("[data-reject]").forEach(button=>button.addEventListener("click",()=>approval(button.dataset.reject,false)));$("codeSearch")?.addEventListener("click",searchCode);$("codeQuery")?.addEventListener("keydown",event=>{if(event.key==="Enter")searchCode()})}
  async function approval(id,approve){if(!confirm(`${approve?"Approve":"Reject"} ${id}? This changes approval state only and does not execute the external action.`))return;try{await api(`/api/approvals/${approve?"approve":"reject"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approval_id:id})});await load()}catch(error){alert(error.message)}}
  async function searchCode(){const query=$("codeQuery")?.value?.trim();if(!query)return;const host=$("codeResults");host.className="loading";host.textContent="Searching static AST index…";try{const payload=await api(`/api/code?q=${encodeURIComponent(query)}`);const rows=payload.results||[];host.className="";host.innerHTML=table(["SCORE","PATH","FUNCTIONS","CLASSES","IMPORTS"],rows.map(row=>`<tr><td>${esc(row.score)}</td><td><b>${esc(row.path)}</b></td><td>${esc((row.functions||[]).slice(0,12).join(", "))}</td><td>${esc((row.classes||[]).slice(0,8).join(", "))}</td><td>${esc((row.imports||[]).slice(0,10).join(", "))}</td></tr>`))}catch(error){host.className="error";host.textContent=error.message}}
  function render(){document.querySelectorAll("[data-section]").forEach(button=>button.classList.toggle("active",button.dataset.section===section));const title=section.replaceAll("_"," ").toUpperCase();$("sectionTitle").textContent=title;$("sectionKicker").textContent=section==="overview"?"SYSTEM COMPLETION":"V7 GOVERNED INTELLIGENCE";$("content").innerHTML=(renderers[section]||overview)();bind()}
  async function load(){const host=$("content");host.innerHTML='<div class="loading">Refreshing verified local state…</div>';try{state=await api("/api/overview");$("serviceState").textContent=`${state.service} · ${state.version}`;$("updatedAt").textContent=new Date().toLocaleString();$("sectionMessage").textContent=`Repository-controlled completion ${num(state.completion?.repository_completion_percent||0)}%. External infrastructure remains separately blocked where applicable.`;render()}catch(error){host.innerHTML=`<div class="error">${esc(error.message)}</div>`}}
  document.querySelectorAll("[data-section]").forEach(button=>button.addEventListener("click",()=>{section=button.dataset.section;render()}));$("refresh").addEventListener("click",load);load();
})();
