(()=>{
  "use strict";
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const num=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:d}):"—";
  let active=null;

  function installStyle(){
    if($("v10AdvancedStyle"))return;
    const style=document.createElement("style");style.id="v10AdvancedStyle";style.textContent=`
      .v10-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:14px}
      .v10-card{border:1px solid #1b3e50;background:#07151e;border-radius:10px;padding:12px;min-width:0}.v10-card span{display:block;color:#769baa;font-size:10px;letter-spacing:.08em}.v10-card b{display:block;color:#e5f9ff;font-size:18px;margin-top:4px;overflow-wrap:anywhere}
      .v10-list{display:grid;gap:8px}.v10-row{border:1px solid #173849;background:#07131b;border-radius:9px;padding:10px;overflow-wrap:anywhere}.v10-row h3{margin:0 0 6px;font-size:12px;color:#dff8ff}.v10-row small{color:#7fa4b4}.v10-row pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#050d13;border:1px solid #112b38;border-radius:7px;padding:8px;max-height:220px;overflow:auto;font-size:9px;color:#91b7c6}
      .v10-badge{display:inline-block;border:1px solid #285267;border-radius:999px;padding:3px 7px;font-size:9px;margin-right:5px}.v10-ok{color:#75efae}.v10-warn{color:#ffc271}.v10-bad{color:#ff7e87}.v10-toolbar{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.v10-toolbar input{flex:1;min-width:220px;background:#06111a;color:#dff8ff;border:1px solid #21485c;border-radius:7px;padding:9px}.v10-toolbar button{min-height:34px}
      @media(max-width:1100px){.v10-grid{grid-template-columns:1fr 1fr}}@media(max-width:700px){.v10-grid{grid-template-columns:1fr}}
    `;document.head.appendChild(style);
  }
  async function api(url,options={}){const r=await fetch(url,options);let p={};try{p=await r.json()}catch{}if(!r.ok||p.success===false)throw new Error(p.message||p.error||`HTTP ${r.status}`);return p}
  const cards=rows=>`<div class="v10-grid">${rows.map(([a,b,k=""])=>`<article class="v10-card"><span>${esc(a)}</span><b class="${k}">${esc(b)}</b></article>`).join("")}</div>`;
  function activate(id,title,msg){active=id;document.querySelectorAll(".nav button").forEach(b=>b.classList.remove("active"));$(id)?.classList.add("active");$("sectionKicker").textContent="V10 ADVANCED AUTONOMY";$("sectionTitle").textContent=title;$("sectionMessage").textContent=msg;$("content").innerHTML='<div class="loading">Refreshing governed state…</div>';}

  async function criticView(){activate("criticNav","CRITIC + EVIDENCE","System-level verification plane and bounded provenance ledger. This is not agent #30.");try{const [c,e]=await Promise.all([api("/api/critic"),api("/api/evidence")]);const last=c.last_verification||{};const rows=(e.records||[]).slice().reverse().slice(0,30);$("content").innerHTML=cards([["VERDICT",last.verdict||"NO VERIFICATION",last.verdict==="VERIFIED"?"v10-ok":"v10-warn"],["CONFIDENCE",last.confidence==null?"—":num(Number(last.confidence)*100,1)+"%"],["VERIFIED",num(c.verified_count||0,0)],["EVIDENCE RECORDS",num(e.count||0,0)]])+`<section class="section"><div class="section-head"><h2>Last verification</h2><small>Progression is allowed only when the required evidence contract passes.</small></div><pre>${esc(JSON.stringify(last,null,2))}</pre></section><section class="section"><div class="section-head"><h2>Evidence ledger</h2></div><div class="v10-list">${rows.length?rows.map(r=>`<article class="v10-row"><h3>${esc(r.kind)} · ${esc(r.subject)}</h3><span class="v10-badge">${esc(r.state)}</span><span class="v10-badge">${esc(r.freshness)}</span><small>${esc(r.source)} · confidence ${num(Number(r.confidence||0)*100,1)}%</small><pre>${esc(r.claim||"")}</pre></article>`).join(""):'<div class="empty">No evidence records yet.</div>'}</div></section>`;}catch(e){$("content").innerHTML=`<div class="error">${esc(e.message)}</div>`}}

  async function engineeringView(){activate("engineeringGovNav","ENGINEERING GOVERNANCE","Inspect → plan → bounded checks → critic → review packet. No automatic merge, push or production rewrite.");try{const p=await api("/api/engineering"),s=p.status||{},r=p.repository||{};$("content").innerHTML=cards([["BRANCH",r.branch||"—"],["HEAD",String(r.head||"—").slice(0,12)],["WORKTREE",r.clean?"CLEAN":"DIRTY",r.clean?"v10-ok":"v10-warn"],["AUTO EDITING",s.capabilities?.automatic_editing?"ON":"OFF","v10-ok"]])+`<section class="section"><div class="section-head"><h2>Governed engineering plan</h2><small>Planning is repository-grounded; automatic production rewrite is disabled.</small></div><div class="v10-toolbar"><input id="v10EngRequest" placeholder="Describe the repository change"><button id="v10EngPlan">PLAN</button><button id="v10EngReview">REVIEW CURRENT DIFF</button></div><div id="v10EngResult" class="empty">No engineering action requested.</div></section><section class="section"><div class="section-head"><h2>Repository evidence</h2></div><pre>${esc(JSON.stringify(r,null,2))}</pre></section>`;$("v10EngPlan")?.addEventListener("click",async()=>{const q=$("v10EngRequest").value.trim();if(!q)return;try{$("v10EngResult").textContent="Planning…";const x=await api("/api/engineering/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request:q})});$("v10EngResult").innerHTML=`<pre>${esc(JSON.stringify(x,null,2))}</pre>`}catch(e){$("v10EngResult").textContent=e.message}});$("v10EngReview")?.addEventListener("click",async()=>{try{$("v10EngResult").textContent="Building review packet…";const x=await api("/api/engineering/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({request:$("v10EngRequest").value.trim()})});$("v10EngResult").innerHTML=`<pre>${esc(JSON.stringify(x,null,2))}</pre>`}catch(e){$("v10EngResult").textContent=e.message}});}catch(e){$("content").innerHTML=`<div class="error">${esc(e.message)}</div>`}}

  async function systemView(){activate("systemDiagNav","SYSTEM DIAGNOSTICS","Service health, incidents and bounded recovery proposals. Unknown processes are never killed.");try{const p=await api("/api/system-diagnostics");const services=p.services||[],inc=p.incidents||[],props=p.recovery_proposals||[];$("content").innerHTML=cards([["OVERALL",p.overall||"—",p.overall==="READY"?"v10-ok":"v10-warn"],["SERVICES READY",`${services.filter(x=>x.healthy).length}/${services.length}`],["INCIDENTS",num(inc.length,0)],["DISK FREE",num(Number(p.disk?.free_fraction||0)*100,1)+"%"]])+`<section class="section"><div class="section-head"><h2>Services</h2></div><div class="v10-list">${services.map(x=>`<article class="v10-row"><h3>${esc(x.name)} · ${esc(x.state)}</h3><span class="v10-badge ${x.healthy?"v10-ok":"v10-warn"}">PORT ${esc(x.port)}</span><small>${esc(x.health_url)}</small></article>`).join("")}</div></section><section class="section"><div class="section-head"><h2>Recovery proposals</h2><small>Only two reversible internal recoveries are executable automatically.</small></div><div class="v10-toolbar"><button data-recover="RECOVER_EXPIRED_MISSION_LEASES">RECOVER EXPIRED LEASES</button><button data-recover="REFRESH_WORLD_MODEL">REFRESH WORLD MODEL</button></div><div class="v10-list">${props.length?props.map(x=>`<article class="v10-row"><h3>${esc(x.action)} · ${esc(x.target)}</h3><small>${esc(x.reason)} · automatic=${esc(x.automatic)}</small></article>`).join(""):'<div class="empty">No recovery proposals.</div>'}</div></section>`;document.querySelectorAll("[data-recover]").forEach(b=>b.addEventListener("click",async()=>{try{await api("/api/system/recover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:b.dataset.recover})});systemView()}catch(e){alert(e.message)}}));}catch(e){$("content").innerHTML=`<div class="error">${esc(e.message)}</div>`}}

  async function tradingView(){activate("tradingGovNav","TRADING GOVERNANCE","Paper-learning, mistake hypotheses, research proposals and champion/challenger governance. Live execution remains locked.");try{const p=await api("/api/trading-governance"),props=p.research_proposals||[],m=p.mistakes?.ranked_mistakes||[],g=p.strategy_governance||{};$("content").innerHTML=cards([["RESEARCH PROPOSALS",num(props.length,0)],["STRATEGY RECORDS",num((g.records||[]).length,0)],["PAPER CHAMPIONS",num(Object.keys(g.paper_champions||{}).length,0)],["LIVE EXECUTION","LOCKED","v10-bad"]])+`<section class="section"><div class="section-head"><h2>Research proposals</h2><small>Proposals may become paper research only after robust validation.</small></div><div class="v10-list">${props.length?props.map(x=>`<article class="v10-row"><h3>${esc(x.topic)} · ${esc(x.priority)}</h3><span class="v10-badge">${esc(x.kind)}</span><small>Evidence ${esc(x.evidence_count)} · ${esc(x.action)}</small></article>`).join(""):'<div class="empty">No new governed research proposal.</div>'}</div></section><section class="section"><div class="section-head"><h2>Ranked paper mistakes</h2></div><pre>${esc(JSON.stringify(m.slice(0,20),null,2))}</pre></section><section class="section"><div class="section-head"><h2>Critic</h2></div><pre>${esc(JSON.stringify(p.critic||{},null,2))}</pre></section>`;}catch(e){$("content").innerHTML=`<div class="error">${esc(e.message)}</div>`}}

  function bind(){const map={criticNav:criticView,engineeringGovNav:engineeringView,systemDiagNav:systemView,tradingGovNav:tradingView};Object.entries(map).forEach(([id,fn])=>$(id)?.addEventListener("click",fn));document.querySelectorAll("[data-section],#worldNav").forEach(b=>b.addEventListener("click",()=>{active=null;Object.keys(map).forEach(id=>$(id)?.classList.remove("active"))}));}
  installStyle();bind();
})();
