const $=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);
let moduleName=params.get("module")||"structure";
let expiryValue=params.get("expiry")||"";
const TITLES={"option-chain":"LIVE OPTION CHAIN","oi-iv":"OPEN INTEREST / IMPLIED VOLATILITY",fvg:"FAIR VALUE GAP INTELLIGENCE",structure:"MARKET STRUCTURE",heatmaps:"MULTI-MARKET HEATMAPS","portfolio-risk":"PAPER PORTFOLIO RISK","trade-journal":"TRADING JOURNAL"};
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const num=(value,digits=2)=>Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{maximumFractionDigits:digits}):"—";
const json=value=>esc(JSON.stringify(value??{},null,2));

function syncQuery(){params.set("module",moduleName);params.set("symbol",$("symbolSelect").value);params.set("universe",$("universeSelect").value);if(expiryValue)params.set("expiry",expiryValue);else params.delete("expiry");history.replaceState(null,"",`${location.pathname}?${params}`)}
function cards(entries){return `<div class="cards">${entries.map(([label,value,klass=""])=>`<article class="card"><span class="label">${esc(label)}</span><strong class="value ${klass}">${esc(value)}</strong></article>`).join("")}</div>`}
function renderOptions(payload){const analytics=payload.chain_analytics||{};const chain=payload.chain||[];const maxPain=analytics.max_pain?.strike??analytics.max_pain;return cards([["UNDERLYING / SPOT",`${payload.symbol} · ${num(payload.spot)}`],["EXPIRY",payload.expiry?.date||payload.expiry?.expiry||payload.expiry||"NEAREST"],["PCR OI",num(payload.pcr_oi??analytics.pcr_oi,3)],["MAX PAIN",num(maxPain)],["VISIBLE / LISTED",`${chain.length} / ${payload.total_contracts_available??chain.length}`],["GREEKS",payload.greeks_status||"PROVIDER FIELDS"]])+`<div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>TYPE</th><th>STRIKE</th><th>LTP</th><th>BID</th><th>ASK</th><th>OI</th><th>CHG OI</th><th>VOLUME</th><th>IV</th><th>DELTA</th><th>GAMMA</th><th>THETA</th><th>VEGA</th></tr></thead><tbody>${chain.map(row=>`<tr><td>${esc(row.option_type)}</td><td>${num(row.strike)}</td><td>${num(row.ltp??row.last_price)}</td><td>${num(row.bid)}</td><td>${num(row.ask)}</td><td>${num(row.open_interest,0)}</td><td>${num(row.change_in_oi,0)}</td><td>${num(row.volume,0)}</td><td>${num(row.iv)}</td><td>${num(row.delta??row.greeks?.delta,3)}</td><td>${num(row.gamma??row.greeks?.gamma,5)}</td><td>${num(row.theta??row.greeks?.theta,3)}</td><td>${num(row.vega??row.greeks?.vega,3)}</td></tr>`).join("")}</tbody></table></div>`}
function renderFeatures(payload,kind){const rows=payload.timeframes||[];return `<div class="timeframes">${rows.map(row=>{const focus=kind==="fvg"?{fair_value_gaps:row.fair_value_gaps,supply_demand:row.supply_demand}:{structure:row.structure,support_resistance:row.support_resistance,patterns:row.patterns};return `<article class="timeframe"><div class="journal-head"><b>${esc(row.timeframe||"TIMEFRAME")}</b><span>${row.fresh===false?"STALE":"VERIFIED"}</span></div><pre>${json(focus)}</pre></article>`}).join("")}</div>`+cards([["CANDIDATE",payload.decision?.candidate_side||"WAIT"],["SCORE",num(payload.decision?.score)],["REGIME",payload.decision?.regime||"—"],["RISK / REWARD",num(payload.decision?.risk_reward)]])}
function renderHeatmap(payload){if(!(payload.rows||[]).length)return `<div class="empty">${esc(payload.message)}</div>`;return `<div class="heatmap">${payload.rows.map(row=>{const change=Number(row.percent_change);const cls=change>0?"up":change<0?"down":"flat";return `<article class="heat ${cls}"><b>${esc(row.symbol)}</b><strong>${num(change)}%</strong><small>${esc(row.state||row.direction||"NO EDGE")} · score ${num(row.score)}</small></article>`}).join("")}</div>`}
function renderRisk(payload){const p=payload.portfolio||{};return cards([["PAPER EQUITY",num(p.equity)],["TOTAL P&L",num(p.total_pnl),Number(p.total_pnl)>=0?"positive":"negative"],["OPEN POSITIONS",`${p.open_count||0} / ${p.max_open_positions||0}`],["GROSS EXPOSURE",num(p.gross_exposure)],["RISK AT STOPS",`${num(p.risk_at_stops)} · ${num(p.risk_percent_of_equity)}%`],["DRAWDOWN",`${num(p.drawdown)} · ${num(p.drawdown_percent)}%`]])+`<div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>SYMBOL</th><th>SIDE</th><th>QTY</th><th>ENTRY</th><th>MARK</th><th>STOP</th><th>TARGET</th><th>P&L</th></tr></thead><tbody>${(p.positions||[]).map(row=>`<tr><td>${esc(row.symbol)}</td><td>${esc(row.side)}</td><td>${num(row.quantity,6)}</td><td>${num(row.entry??row.entry_price)}</td><td>${num(row.mark??row.mark_price)}</td><td>${num(row.stop??row.stop_price)}</td><td>${num(row.target??row.target_price)}</td><td class="${Number(row.pnl??row.unrealized_pnl)>=0?"positive":"negative"}">${num(row.pnl??row.unrealized_pnl)}</td></tr>`).join("")}</tbody></table></div>`}
function snapshotSvg(bars){if(!Array.isArray(bars)||bars.length<2)return `<div class="empty">Frozen entry chart snapshot was not captured for this older trade.</div>`;const rows=bars.slice(-80);const low=Math.min(...rows.map(r=>Number(r.low)));const high=Math.max(...rows.map(r=>Number(r.high)));const range=Math.max(high-low,.000001);const w=800,h=200,step=w/rows.length;const candles=rows.map((r,i)=>{const x=i*step+step/2;const y=v=>10+(high-Number(v))/range*(h-20);const open=y(r.open),close=y(r.close),top=Math.min(open,close),height=Math.max(1,Math.abs(open-close));const color=Number(r.close)>=Number(r.open)?"#72f2aa":"#ff7187";return `<line x1="${x}" y1="${y(r.high)}" x2="${x}" y2="${y(r.low)}" stroke="${color}"/><rect x="${x-step*.28}" y="${top}" width="${Math.max(2,step*.56)}" height="${height}" fill="${color}"/>`}).join("");return `<div class="chart-snapshot"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${candles}</svg></div>`}
function renderJournal(payload){const trades=payload.closed_positions||[];if(!trades.length)return `<div class="empty">No closed synthetic paper trades are available.</div>`;return `<div class="journal-grid">${trades.map(row=>{const meta=row.metadata||{};const patterns=meta.chart_patterns||[];const indicators=meta.indicator_snapshot||meta.feature_snapshot?.indicators||{};const bars=meta.entry_chart_snapshot?.bars||meta.entry_chart_snapshot||[];return `<article class="journal-card"><div class="journal-head"><b>${esc(row.symbol)} · ${esc(row.side)} · ${esc(row.timeframe||meta.timeframe||"")}</b><span class="${Number(row.realized_pnl)>=0?"positive":"negative"}">${num(row.realized_pnl)} · ${esc(row.exit_reason||"")}</span></div><p class="journal-reason">${esc(meta.entry_reason||meta.message||"Durable entry rationale was not recorded for this older trade.")}</p><div class="tags"><span class="tag">${esc(row.strategy||meta.strategy_id||"STRATEGY UNKNOWN")}</span><span class="tag">score ${num(row.score??meta.score)}</span><span class="tag">entry ${num(row.entry)}</span><span class="tag">SL ${num(row.stop)}</span><span class="tag">target ${num(row.target)}</span><span class="tag">MFE ${num(row.mfe_r)}R</span><span class="tag">MAE ${num(row.mae_r)}R</span>${patterns.map(p=>`<span class="tag">${esc(p.name||p.pattern||p)}</span>`).join("")}</div>${snapshotSvg(bars)}<details><summary>FULL ENTRY EVIDENCE</summary><pre>${json({votes:meta.votes,decisions:meta.decisions,regime:meta.regime,risk_model:meta.risk_model,exit_policy:meta.exit_policy,indicators,patterns,contradictions:meta.contradictions})}</pre></details></article>`}).join("")}</div>`}
function render(payload){if(!payload.success){const login=/FYERS/i.test(payload.message||"")?'<button id="moduleFyersLogin" type="button">OPEN FYERS DAILY LOGIN</button>':"";return `<div class="error">${esc(payload.message||"Verified module data is unavailable.")}${login}</div>`}if(["option-chain","oi-iv"].includes(moduleName))return renderOptions(payload);if(["structure","fvg"].includes(moduleName))return renderFeatures(payload,moduleName);if(moduleName==="heatmaps")return renderHeatmap(payload);if(moduleName==="portfolio-risk")return renderRisk(payload);if(moduleName==="trade-journal")return renderJournal(payload);return `<pre>${json(payload)}</pre>`}
function updateExpiryControl(payload){const select=$("expirySelect");const isOptions=["option-chain","oi-iv"].includes(moduleName);select.hidden=!isOptions;if(!isOptions)return;const values=Array.isArray(payload.available_expiries)?payload.available_expiries:[];const selected=payload.expiry?.date||payload.expiry?.expiry||payload.expiry||expiryValue||"";select.replaceChildren(new Option("NEAREST EXPIRY",""),...values.map(value=>new Option(value,value)));if(values.includes(String(selected)))select.value=String(selected);else select.value="";expiryValue=select.value}
async function launchFyersLogin(){const button=$("moduleFyersLogin");if(button){button.disabled=true;button.textContent="OPENING LOGIN…"}try{const response=await fetch("/api/fyers/login",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const payload=await response.json();$("moduleMessage").textContent=payload.message||"FYERS login opened in a local terminal."}catch(error){$("moduleMessage").textContent=error.message}}
async function load(){syncQuery();document.querySelectorAll("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===moduleName));$("moduleTitle").textContent=TITLES[moduleName]||moduleName.toUpperCase();$("moduleContent").innerHTML='<div class="loading">Loading verified evidence…</div>';const q=new URLSearchParams({module:moduleName,symbol:$("symbolSelect").value,universe:$("universeSelect").value,profile:"intraday"});if(expiryValue)q.set("expiry",expiryValue);try{const response=await fetch(`/api/intelligence/module?${q}`);const payload=await response.json();updateExpiryControl(payload);$("moduleMessage").textContent=payload.message||"Module data loaded.";$("sourceState").textContent=`SOURCE: ${payload.source||payload.provider||"LOCAL GOVERNED ENGINE"}`;$("generatedState").textContent=payload.generated_at?new Date(payload.generated_at).toLocaleString():"CURRENT SNAPSHOT";$("moduleContent").innerHTML=render(payload);$("moduleFyersLogin")?.addEventListener("click",launchFyersLogin)}catch(error){$("moduleContent").innerHTML=`<div class="error">${esc(error.message)}</div>`}}
document.querySelectorAll("[data-module]").forEach(button=>button.addEventListener("click",()=>{moduleName=button.dataset.module;load()}));$("refreshButton").addEventListener("click",load);$("symbolSelect").addEventListener("change",()=>{expiryValue="";load()});$("universeSelect").addEventListener("change",load);$("expirySelect").addEventListener("change",event=>{expiryValue=event.target.value;load()});
$("symbolSelect").value=params.get("symbol")||"NIFTY";$("universeSelect").value=params.get("universe")||"NIFTY50";load();
