# ============================================================
# JARVIS TRADING CONFIGURATION
# ============================================================

TRADING_MODE = "PAPER"

LIVE_TRADING_ENABLED = False

DEFAULT_ACCOUNT_CURRENCY = "INR"

MAX_RISK_PER_TRADE_PERCENT = 1.0

MAX_DAILY_LOSS_PERCENT = 3.0

MAX_PORTFOLIO_EXPOSURE_PERCENT = 50.0

MAX_OPEN_POSITIONS = 10

MIN_RISK_REWARD = 1.5

MAX_LEVERAGE = 1.0

REQUIRE_STOP_LOSS = True

REQUIRE_RISK_APPROVAL = True

ALLOW_OPTIONS = True

ALLOW_FUTURES = True

ALLOW_EQUITIES = True

ALLOW_COMMODITIES = True

ALLOW_CRYPTO = True

DATA_TIMEFRAME_DEFAULT = "1d"

PAPER_STARTING_CAPITAL = 1_000_000.0