from __future__ import annotations

import time

import requests

from config import OLLAMA_MODEL, OLLAMA_TIMEOUT_SECONDS, OLLAMA_URL


class CodingAgent:
    """Local coding assistant grounded in the bounded repository AST index.

    The agent remains advisory.  It does not execute commands or edit files.
    Repository context is generated by static AST parsing, never by importing
    arbitrary target modules.
    """

    def __init__(self):
        self.name = "coding"

    @staticmethod
    def _repository_context(query: str) -> str:
        try:
            from omni.code_intelligence import CODE_INTELLIGENCE

            hits = CODE_INTELLIGENCE.search(str(query or ""), limit=8)
        except Exception:
            hits = []
        if not hits:
            return "No high-confidence repository symbol match was found. Do not invent project files."
        lines = []
        for hit in hits:
            functions = ", ".join(list(hit.get("functions") or [])[:8]) or "none"
            classes = ", ".join(list(hit.get("classes") or [])[:6]) or "none"
            lines.append(
                f"- {hit.get('path')} | functions: {functions} | classes: {classes}"
            )
        return "\n".join(lines)

    def ask(self, query):
        clean = str(query or "").strip()
        repository_context = self._repository_context(clean)
        prompt = f"""
You are JARVIS Coding Agent.

You are a professional software engineer working on the local JARVIS repository.

Rules:
1. Write correct, practical code.
2. Prefer Python unless another language is requested.
3. Explain important parts briefly.
4. Never pretend code was executed if it was not.
5. Never invent files, libraries, APIs, test results, or tool results.
6. If the user asks to modify code, clearly show the replacement.
7. Preserve the existing architecture and safety boundaries.
8. Do not execute shell commands.
9. Do not claim to have changed files.
10. Live broker execution remains locked unless a separately audited execution service exists.
11. Treat the repository index below as hints, not proof of runtime behavior.

READ-ONLY REPOSITORY INDEX MATCHES:
{repository_context}

USER REQUEST:
{clean}
"""
        started = time.perf_counter()
        status = "FAILED"
        try:
            response = requests.post(
                OLLAMA_URL,
                json={
                    "model": OLLAMA_MODEL,
                    "prompt": prompt,
                    "stream": False,
                },
                timeout=max(10.0, float(OLLAMA_TIMEOUT_SECONDS)),
            )
            response.raise_for_status()
            data = response.json()
            result = str(data.get("response") or "").strip()
            status = "SUCCEEDED" if result else "FAILED"
            return result
        except Exception as error:
            return "Coding agent error: " + str(error)
        finally:
            try:
                from omni.model_router_telemetry import MODEL_ROUTER_TELEMETRY

                MODEL_ROUTER_TELEMETRY.record(
                    task_type="coding",
                    profile_id="local_coding_ollama",
                    provider="ollama",
                    model=OLLAMA_MODEL,
                    status=status,
                    latency_ms=(time.perf_counter() - started) * 1000.0,
                    local=True,
                    reason="CodingAgent local advisory request",
                )
            except Exception:
                pass

    def coding(self, query):
        result = self.ask(query)
        return {
            "success": not str(result).startswith("Coding agent error:"),
            "type": "coding",
            "message": result,
            "repository_grounded": True,
            "automatic_editing": False,
            "command_execution": False,
        }


coding_agent = CodingAgent()


def coding(query):
    return coding_agent.coding(query)


if __name__ == "__main__":
    print("=" * 60)
    print("JARVIS CODING AGENT TEST")
    print("=" * 60)
    result = coding("Write a Python function that checks whether a number is prime.")
    print()
    print(result.get("message", result))
